# Generated by Django 5.2.3 on 2025-12-06 21:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Apodo de tu moto (ej. La Furia)', max_length=100)),
                ('make', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('mileage', models.IntegerField(default=0, verbose_name='Kilometraje Actual')),
                ('photo', models.ImageField(blank=True, default='default_motorcycle_photo.jpg', upload_to='moto_photos/')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcar si vendiste o diste de baja la moto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorcycles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100, verbose_name='Servicio a Realizar')),
                ('reminder_type', models.CharField(choices=[('distance', 'Por Kilometraje'), ('date', 'Por Fecha')], default='distance', max_length=20)),
                ('next_service_at_mileage', models.IntegerField(blank=True, null=True, verbose_name='A los Km')),
                ('next_service_date', models.DateField(blank=True, null=True, verbose_name='En la Fecha')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='app.motorcycle')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('aceite_motor', 'Cambio de Aceite de Motor'), ('filtro_aceite', 'Cambio de Filtro de Aceite'), ('filtro_aire', 'Limpieza/Cambio Filtro de Aire'), ('bujias', 'Cambio de Bujías'), ('kit_arrastre', 'Mantenimiento Kit de Arrastre'), ('frenos_delanteros', 'Frenos Delanteros (Pastillas/Líquido)'), ('frenos_traseros', 'Frenos Traseros (Zapatas/Pastillas)'), ('neumaticos', 'Cambio de Neumáticos'), ('bateria', 'Batería'), ('ajuste_valvulas', 'Ajuste de Válvulas'), ('suspension', 'Mantenimiento de Suspensión'), ('otro', 'Otro / Reparación General')], max_length=50, verbose_name='Tipo de Servicio')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Servicio')),
                ('mileage_at_service', models.IntegerField(verbose_name='Kilometraje al momento del servicio')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='app.motorcycle')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='default_profile_pic.jpg', upload_to='profile_pics/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
