# Generated by Django 5.2.3 on 2025-06-15 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('category', models.CharField(max_length=50, verbose_name='Categoría')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tips_images/', verbose_name='Imagen')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Taller')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('latitude', models.FloatField(verbose_name='Latitud')),
                ('longitude', models.FloatField(verbose_name='Longitud')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
            ],
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('mileage', models.PositiveIntegerField(verbose_name='Kilometraje')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apodo')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='motorcycle_photos/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorcycles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100, verbose_name='Tipo de Servicio a Recordar')),
                ('reminder_type', models.CharField(choices=[('distance', 'Por Distancia (km)'), ('date', 'Por Fecha')], max_length=10, verbose_name='Tipo de Recordatorio')),
                ('next_service_at_mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Próximo servicio en (km)')),
                ('next_service_date', models.DateField(blank=True, null=True, verbose_name='Fecha del próximo servicio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Recordatorio Activo')),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='app.motorcycle')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('oil_change', 'Cambio de Aceite'), ('brake_service', 'Servicio de Frenos'), ('tire_replacement', 'Cambio de Llantas'), ('chain_service', 'Servicio de Cadena'), ('general_checkup', 'Revisión General'), ('other', 'Otro')], max_length=50, verbose_name='Tipo de Servicio')),
                ('date', models.DateField(verbose_name='Fecha del Servicio')),
                ('mileage_at_service', models.PositiveIntegerField(verbose_name='Kilometraje en el Servicio')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Costo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='app.motorcycle')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
