# Generated by Django 5.2.3 on 2025-12-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Placa/Matrícula'),
        ),
    ]
