# Generated by Django 5.2.3 on 2025-12-07 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_motorcycle_plate_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='moto_gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.motorcycle')),
            ],
        ),
    ]
