# Generated by Django 5.2.3 on 2025-12-07 21:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_motoimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Viaje')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('distance_km', models.IntegerField(verbose_name='Distancia Recorrida (km)')),
                ('terrain', models.CharField(choices=[('city', 'Ciudad (Tráfico)'), ('highway', 'Carretera / Autopista'), ('mixed', 'Mixto'), ('offroad', 'Off-Road / Tierra')], default='mixed', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='app.motorcycle')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
